

ALTER TABLE RMS13.SMR_INV_CROSS_REF_HEAD
 DROP PRIMARY KEY CASCADE;

DROP TABLE RMS13.SMR_INV_CROSS_REF_HEAD CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_INV_CROSS_REF_HEAD
(
  RECORD_ID    NUMBER(20),
  PAID_INV_NO  VARCHAR2(160 BYTE),
  DUE_DATE     DATE,
  ORDER_NO     NUMBER(10),
  LOCATION     NUMBER(10),
  SDC_INV_AMT  NUMBER(20,4)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RMS13.PK_SMR_INV_CROSS_REF_HEAD ON RMS13.SMR_INV_CROSS_REF_HEAD
(RECORD_ID)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARALLEL ( DEGREE 8 INSTANCES 1 );


CREATE INDEX RMS13.SMR_INV_XREF_I1 ON RMS13.SMR_INV_CROSS_REF_HEAD
(ORDER_NO)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RMS13.SMR_INV_CROSS_REF_HEAD ADD (
  CONSTRAINT PK_SMR_INV_CROSS_REF_HEAD
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX RMS13.PK_SMR_INV_CROSS_REF_HEAD
  ENABLE VALIDATE);

create public synonym SMR_INV_CROSS_REF_HEAD for RMS13.SMR_INV_CROSS_REF_HEAD;

grant, select, insert, update, delete on  SMR_INV_CROSS_REF_HEAD to public;


CREATE TABLE RMS13.SMR_INV_CROSS_REF_DETAIL
(
  RECORD_ID    NUMBER(20),
  VENDOR_ID    VARCHAR2(10 BYTE),
  VENDOR_NAME  VARCHAR2(30 BYTE),
  ORIG_INV_NO  VARCHAR2(150 BYTE),
  DUE_DATE     DATE,
  ORDER_NO     NUMBER(10),
  LOCATION     NUMBER(10),
  STR_INV_AMT  NUMBER(20,4),
  DOC_ID       NUMBER(10)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RMS13.FK_SMR_INV_CROSS_REF_DETAIL ON RMS13.SMR_INV_CROSS_REF_DETAIL
(RECORD_ID)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARALLEL ( DEGREE 8 INSTANCES 1 );


ALTER TABLE RMS13.SMR_INV_CROSS_REF_DETAIL ADD (
  CONSTRAINT FK_SMR_INV_CROSS_REF_DETAIL 
  FOREIGN KEY (RECORD_ID) 
  REFERENCES RMS13.SMR_INV_CROSS_REF_HEAD (RECORD_ID)
  ENABLE VALIDATE);


create public synonym SMR_INV_CROSS_REF_DETAIL for RMS13.SMR_INV_CROSS_REF_DETAIL;

grant, select, insert, update, delete on  SMR_INV_CROSS_REF_DETAIL to public;