
DROP TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_IMP CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_IMP
(
  RECORD_ID                    NUMBER(20),
  GROUP_ID                     CHAR(50 BYTE),
  DOCUMENT_TYPE                CHAR(6 BYTE),
  VENDOR_DOCUMENT_NUMBER       CHAR(30 BYTE),
  VENDOR_TYPE                  CHAR(6 BYTE),
  VENDOR_ID                    CHAR(10 BYTE),
  VENDOR_DOCUMENT_DATE         CHAR(14 BYTE),
  ORDER_NUMBER                 NUMBER(10),
  LOCATION                     NUMBER(10),
  LOCATION_TYPE                CHAR(1 BYTE),
  TERMS                        CHAR(15 BYTE),
  DUE_DATE                     CHAR(14 BYTE),
  PAYMENT_METHOD               CHAR(6 BYTE),
  CURRENCY_CODE                CHAR(3 BYTE),
  EXCHANGE_RATE                NUMBER(12,4),
  TOTAL_COST                   NUMBER(20,4),
  SIGN_INDICATOR_COST          CHAR(1 BYTE),
  TOTAL_VAT_AMOUNT             NUMBER(20,4),
  SIGN_INDICATOR_VAT           CHAR(1 BYTE),
  TOTAL_QUANTITY               NUMBER(12,4),
  SIGN_INDICATOR_QTY           CHAR(1 BYTE),
  TOTAL_DISCOUNT               NUMBER(12,4),
  SIGN_INDICATOR_DISC          CHAR(1 BYTE),
  FREIGHT_TYPE                 CHAR(6 BYTE),
  PAID_IND                     CHAR(1 BYTE),
  MULTI_LOCATION               CHAR(1 BYTE),
  CONSIGNMENT_INDICATOR        CHAR(1 BYTE),
  DEAL_ID                      NUMBER(10),
  DEAL_APPROVAL_INDICATOR      CHAR(1 BYTE),
  RTV_INDICATOR                CHAR(1 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_1  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_2  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_3  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_4  CHAR(90 BYTE),
  CROSS_REF_DOCUMENT_NUMBER    NUMBER(10),
  PROCESSED                    CHAR(1 BYTE),
  CREATE_DATE                  DATE,
  PROCESSED_DATE               DATE,
  ERROR_IND                    CHAR(1 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RMS13.PK_SMR_RMS_INT_EDI_810_HDR_IMP ON RMS13.SMR_RMS_INT_EDI_810_HDR_IMP
(GROUP_ID)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RMS13.SMR_RMS_INT_EDI_810_HDR_IMP_I1 ON RMS13.SMR_RMS_INT_EDI_810_HDR_IMP
(PROCESSED)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_IMP ADD (
  CONSTRAINT PK_SMR_RMS_INT_EDI_810_HDR_IMP
  PRIMARY KEY
  (GROUP_ID)
  USING INDEX RMS13.PK_SMR_RMS_INT_EDI_810_HDR_IMP
  ENABLE VALIDATE);

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_HDR_IMP TO svc_int_rms;

create or replace public synonym SMR_RMS_INT_EDI_810_HDR_IMP for RMS13.SMR_RMS_INT_EDI_810_HDR_IMP;

DROP TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_IMP CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_IMP
(
  RECORD_ID                   NUMBER(20),
  GROUP_ID                    CHAR(50 BYTE),
  UPC                         CHAR(25 BYTE),
  UPC_SUPPLEMENT              NUMBER(5),
  ITEM                        CHAR(25 BYTE),
  VPN                         CHAR(30 BYTE),
  SIGN_INDICATOR_QTY          CHAR(1 BYTE),
  ORIGINAL_DOCUMENT_QUANTITY  NUMBER(12,4),
  SIGN_INDICATOR_COST         CHAR(1 BYTE),
  ORIGINAL_UNIT_COST          NUMBER(20,4),
  ORIGINAL_VAT_CODE           CHAR(6 BYTE),
  ORIGINAL_VAT_RATE           NUMBER(20,10),
  SIGN_INDICATOR_VAT          CHAR(1 BYTE),
  TOTAL_ALLOWANCE             NUMBER(20,4),
  PROCESSED                   CHAR(1 BYTE),
  CREATE_DATE                 DATE,
  PROCESSED_DATE              DATE,
  ERROR_IND                   CHAR(1 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RMS13.PK_SMR_RMS_INT_EDI_810_DTL_IMP ON RMS13.SMR_RMS_INT_EDI_810_DTL_IMP
(GROUP_ID, item)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RMS13.SMR_RMS_INT_EDI_810_DTL_IMP_I1 ON RMS13.SMR_RMS_INT_EDI_810_DTL_IMP
(PROCESSED)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_IMP ADD (
  CONSTRAINT FK_SMR_RMS_INT_EDI_810_DTL_IMP 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES RMS13.SMR_RMS_INT_EDI_810_HDR_IMP (GROUP_ID)
  ENABLE VALIDATE);

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_DTL_IMP TO svc_int_rms;

create or replace public synonym SMR_RMS_INT_EDI_810_DTL_IMP for RMS13.SMR_RMS_INT_EDI_810_DTL_IMP;

DROP TABLE RMS13.SMR_EDI_810_FINAL_FILE_FORMAT CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_EDI_810_FINAL_FILE_FORMAT
(
  SUPPLIER         NUMBER(10),
  FORMAT_REC       VARCHAR2(4000 BYTE),
  HDR_DTL_IND      CHAR(1 BYTE),
  CREATE_DATETIME  DATE
)
TABLESPACE RETEK_INDEX
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RMS13.SMR_EDI_810_FILE_FORMAT_i1 ON RMS13.SMR_EDI_810_FINAL_FILE_FORMAT
(supplier)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_EDI_810_FINAL_FILE_FORMAT TO svc_int_rms;

create or replace public synonym SMR_EDI_810_FINAL_FILE_FORMAT for RMS13.SMR_EDI_810_FINAL_FILE_FORMAT;

------ 

HIST tables


DROP TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_HIST CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_HIST
(
  RECORD_ID                    NUMBER(20),
  GROUP_ID                     CHAR(50 BYTE),
  DOCUMENT_TYPE                CHAR(6 BYTE),
  VENDOR_DOCUMENT_NUMBER       CHAR(30 BYTE),
  VENDOR_TYPE                  CHAR(6 BYTE),
  VENDOR_ID                    CHAR(10 BYTE),
  VENDOR_DOCUMENT_DATE         CHAR(14 BYTE),
  ORDER_NUMBER                 NUMBER(10),
  LOCATION                     NUMBER(10),
  LOCATION_TYPE                CHAR(1 BYTE),
  TERMS                        CHAR(15 BYTE),
  DUE_DATE                     CHAR(14 BYTE),
  PAYMENT_METHOD               CHAR(6 BYTE),
  CURRENCY_CODE                CHAR(3 BYTE),
  EXCHANGE_RATE                NUMBER(12,4),
  TOTAL_COST                   NUMBER(20,4),
  SIGN_INDICATOR_COST          CHAR(1 BYTE),
  TOTAL_VAT_AMOUNT             NUMBER(20,4),
  SIGN_INDICATOR_VAT           CHAR(1 BYTE),
  TOTAL_QUANTITY               NUMBER(12,4),
  SIGN_INDICATOR_QTY           CHAR(1 BYTE),
  TOTAL_DISCOUNT               NUMBER(12,4),
  SIGN_INDICATOR_DISC          CHAR(1 BYTE),
  FREIGHT_TYPE                 CHAR(6 BYTE),
  PAID_IND                     CHAR(1 BYTE),
  MULTI_LOCATION               CHAR(1 BYTE),
  CONSIGNMENT_INDICATOR        CHAR(1 BYTE),
  DEAL_ID                      NUMBER(10),
  DEAL_APPROVAL_INDICATOR      CHAR(1 BYTE),
  RTV_INDICATOR                CHAR(1 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_1  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_2  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_3  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_4  CHAR(90 BYTE),
  CROSS_REF_DOCUMENT_NUMBER    NUMBER(10),
  PROCESSED                    CHAR(1 BYTE),
  CREATE_DATE                  DATE,
  PROCESSED_DATE               DATE,
  ERROR_IND                    CHAR(1 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RMS13.PK_SMR_RMS_INT_EDI_810_HDR_HIS ON RMS13.SMR_RMS_INT_EDI_810_HDR_HIST
(GROUP_ID)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RMS13.SMR_RMS_INT_EDI_810_HDR_HISI1 ON RMS13.SMR_RMS_INT_EDI_810_HDR_HIST
(PROCESSED)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_HIST ADD (
  CONSTRAINT PK_SMR_RMS_INT_EDI_810_HDR_HIS
  PRIMARY KEY
  (GROUP_ID)
  USING INDEX RMS13.PK_SMR_RMS_INT_EDI_810_HDR_HIS
  ENABLE VALIDATE);

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_HDR_HIST TO svc_int_rms;

create or replace public synonym SMR_RMS_INT_EDI_810_HDR_HIST for RMS13.SMR_RMS_INT_EDI_810_HDR_HIST;

DROP TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_HIST CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_HIST
(
  RECORD_ID                   NUMBER(20),
  GROUP_ID                    CHAR(50 BYTE),
  UPC                         CHAR(25 BYTE),
  UPC_SUPPLEMENT              NUMBER(5),
  ITEM                        CHAR(25 BYTE),
  VPN                         CHAR(30 BYTE),
  SIGN_INDICATOR_QTY          CHAR(1 BYTE),
  ORIGINAL_DOCUMENT_QUANTITY  NUMBER(12,4),
  SIGN_INDICATOR_COST         CHAR(1 BYTE),
  ORIGINAL_UNIT_COST          NUMBER(20,4),
  ORIGINAL_VAT_CODE           CHAR(6 BYTE),
  ORIGINAL_VAT_RATE           NUMBER(20,10),
  SIGN_INDICATOR_VAT          CHAR(1 BYTE),
  TOTAL_ALLOWANCE             NUMBER(20,4),
  PROCESSED                   CHAR(1 BYTE),
  CREATE_DATE                 DATE,
  PROCESSED_DATE              DATE,
  ERROR_IND                   CHAR(1 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX RMS13.PK_SMR_RMS_INT_EDI_810_DTL_HIS ON RMS13.SMR_RMS_INT_EDI_810_DTL_HIST
(GROUP_ID, item)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RMS13.SMR_RMS_INT_EDI_810_DTL_HIS_I1 ON RMS13.SMR_RMS_INT_EDI_810_DTL_HIST
(PROCESSED)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_HIST ADD (
  CONSTRAINT FK_SMR_RMS_INT_EDI_810_DTL_HIS
  FOREIGN KEY (GROUP_ID) 
  REFERENCES RMS13.SMR_RMS_INT_EDI_810_HDR_HIST (GROUP_ID)
  ENABLE VALIDATE);

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_DTL_HIST TO svc_int_rms;

create or replace public synonym SMR_RMS_INT_EDI_810_DTL_HIST for RMS13.SMR_RMS_INT_EDI_810_DTL_HIST;

DROP TABLE RMS13.SMR_EDI_810_FINAL_FILE_HIST CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_EDI_810_FINAL_FILE_HIST
(
 SUPPLIER         NUMBER(10),
  FORMAT_REC       VARCHAR2(4000 BYTE),
  HDR_DTL_IND      CHAR(1 BYTE),
  CREATE_DATETIME  DATE,
  ROW_NUM          NUMBER(10)
) 
TABLESPACE RETEK_INDEX
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX RMS13.SMR_EDI_810_FILE_HIST_i1 ON RMS13.SMR_EDI_810_FINAL_FILE_HIST
(supplier)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_EDI_810_FINAL_FILE_HIST TO svc_int_rms;

create or replace public synonym SMR_EDI_810_FINAL_FILE_HIST for RMS13.SMR_EDI_810_FINAL_FILE_HIST;



CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_HDR_STG
(
  RECORD_DESCRIPTOR            CHAR(5 BYTE),
  LINE_ID                      CHAR(10 BYTE),
  TRANSACTION_NUMBER           CHAR(10 BYTE),
  DOCUMENT_TYPE                CHAR(6 BYTE),
  VENDOR_DOCUMENT_NUMBER       CHAR(30 BYTE),
  GROUP_ID                     CHAR(10 BYTE),
  VENDOR_TYPE                  CHAR(6 BYTE),
  VENDOR_ID                    CHAR(10 BYTE),
  VENDOR_DOCUMENT_DATE         CHAR(14 BYTE),
  ORDER_NUMBER_RTV_NUMBER      CHAR(10 BYTE),
  LOCATION                     CHAR(10 BYTE),
  LOCATION_TYPE                CHAR(1 BYTE),
  TERMS                        CHAR(15 BYTE),
  DUE_DATE                     CHAR(14 BYTE),
  PAYMENT_METHOD               CHAR(6 BYTE),
  CURRENCY_CODE                CHAR(3 BYTE),
  EXCHANGE_RATE                CHAR(12 BYTE),
  SIGN_INDICATOR_COST          CHAR(1 BYTE),
  TOTAL_COST                   CHAR(20 BYTE),
  SIGN_INDICATOR_VAT           CHAR(1 BYTE),
  TOTAL_VAT_AMOUNT             CHAR(20 BYTE),
  SIGN_INDICATOR_QTY           CHAR(1 BYTE),
  TOTAL_QUANTITY               CHAR(12 BYTE),
  SIGN_INDICATOR_DISC          CHAR(1 BYTE),
  TOTAL_DISCOUNT               CHAR(12 BYTE),
  FREIGHT_TYPE                 CHAR(6 BYTE),
  PAID_IND                     CHAR(1 BYTE),
  MULTI_LOCATION               CHAR(1 BYTE),
  CONSIGNMENT_INDICATOR        CHAR(1 BYTE),
  DEAL_ID                      CHAR(10 BYTE),
  DEAL_APPROVAL_INDICATOR      CHAR(1 BYTE),
  RTV_INDICATOR                CHAR(1 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_1  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_2  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_3  CHAR(90 BYTE),
  CUSTOM_DOCUMENT_REFERENCE_4  CHAR(90 BYTE),
  CROSS_REFERENCE_DOC_NUMBER   CHAR(10 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

create public synonym SMR_RMS_INT_EDI_810_HDR_STG for SMR_RMS_INT_EDI_810_HDR_STG;

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_HDR_STG TO svc_int_rms;


CREATE TABLE RMS13.SMR_RMS_INT_EDI_810_DTL_STG
(
  RECORD_DESCRIPTOR          CHAR(5 BYTE),
  LINE_ID                    CHAR(10 BYTE),
  TRANSACTION_NUMBER         CHAR(10 BYTE),
  UPC                        CHAR(25 BYTE),
  UPC_SUPPLEMENT             CHAR(5 BYTE),
  ITEM                       CHAR(25 BYTE),
  VPN                        CHAR(30 BYTE),
  SIGN_INDICATOR_QTY         CHAR(1 BYTE),
  ORIGINALDOCUMENT_QUANTITY  CHAR(12 BYTE),
  SIGN_INDICATOR             CHAR(1 BYTE),
  ORIGINAL_UNIT_COST         CHAR(20 BYTE),
  ORIGINAL_VAT_CODE          CHAR(6 BYTE),
  ORIGINAL_VAT_RATE          CHAR(20 BYTE),
  SIGN_INDICATOR_VAT         CHAR(1 BYTE),
  TOTAL_ALLOWANCE            CHAR(20 BYTE)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE  INDEX RMS13.SMR_RMS_INT_EDI_810_DTL_STG_I1 ON RMS13.SMR_RMS_INT_EDI_810_DTL_STG
(LINE_ID)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

            
create public synonym SMR_RMS_INT_EDI_810_HDR_STG for SMR_RMS_INT_EDI_810_DTL_STG;

GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_EDI_810_DTL_STG TO svc_int_rms;

alter table smr_system_options add (MATCH_DELAY_DAYS number(4));

alter table smr_system_options add (ALLOW_XDOCK_ALLOC  char(1));