DROP TABLE RMS13.SMR_RMS_INT_ALLOC_TSF_EXP CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_ALLOC_TSF_EXP
(
  RECORD_ID       NUMBER(3),
  GROUP_ID        VARCHAR2(50),
  TSF_NO          NUMBER(10),
  ALLOC_NO        NUMBER(10),
  ORDER_NO        NUMBER(10),
  FROM_LOC         NUMBER(10),
  TO_LOC          NUMBER(10),
  STORE_WH        NUMBER(10),
  SOURCE          CHAR(1 BYTE),
  INVENTORY_TYPE  CHAR(1 BYTE),
  TSF_TYPE	  CHAR (2 BYTE),
  DIVISION        NUMBER(4),
  DEPT            NUMBER(4),
  DATE_EXPECTED   DATE,
  ITEM            VARCHAR2(25 BYTE),
  QTY             NUMBER(20,4),
  STATUS          CHAR(1 BYTE),
  CREATE_DATETIME DATE
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


create or replace public synonym SMR_RMS_INT_ALLOC_TSF_EXP for RMS13.SMR_RMS_INT_ALLOC_TSF_EXP;

CREATE INDEX RMS13.SMR_RMS_INT_ALLOC_TSF_EXP_I1 ON RMS13.SMR_RMS_INT_ALLOC_TSF_EXP
(ALLOC_NO)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE INDEX RMS13.SMR_RMS_INT_ALLOC_TSF_EXP_I2 ON RMS13.SMR_RMS_INT_ALLOC_TSF_EXP
(TSF_NO)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
 
GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_ALLOC_TSF_EXP TO svc_int_rms;

DROP TABLE RMS13.SMR_RMS_INT_ALLOC_STG CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_ALLOC_STG
(
  WH              NUMBER(10),
  ALLOC_NO        NUMBER(10),
  ORDER_NO        NUMBER(10),
  SOURCE          CHAR(1 BYTE),
  DIVISION        NUMBER(4),
  DEPT            NUMBER(4),
  STORE           NUMBER(10),
  STORE_WH        NUMBER(10),
  ORDER_DATE      DATE,
  DATE_EXPECTED   DATE,
  ITEM            VARCHAR2(25 BYTE),
  QTY             NUMBER(20,4),
  STATUS          CHAR(1 BYTE),
  CREATE_DATETIME DATE
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_ALLOC_STG TO svc_int_rms;


DROP TABLE RMS13.SMR_RMS_INT_TSF_STG CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_TSF_STG
(
  TSF_NO        NUMBER(10),
  FROM_LOC        NUMBER(10),
  TO_LOC        NUMBER(10),
  INVENTORY_TYPE  CHAR(1),
  TSF_TYPE          CHAR(4 BYTE),
  DIVISION        NUMBER(4),
  DEPT            NUMBER(4),
  DATE_EXPECTED   DATE,
  ITEM            VARCHAR2(25 BYTE),
  QTY             NUMBER(20,4),
  STATUS          CHAR(1 BYTE),
  CREATE_DATETIME DATE
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   6
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_TSF_STG TO svc_int_rms;



DROP TABLE RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP CASCADE CONSTRAINTS;

CREATE TABLE RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP
(
  RECORD_ID       NUMBER(3),
  GROUP_ID       VARCHAR2(50 BYTE),
  TRAN_DATE      DATE,
  FROM_LOC       NUMBER(10),
  FROM_LOC_TYPE  CHAR(1 BYTE),
  TO_LOC         NUMBER(10),
  TO_LOC_TYPE    CHAR(1 BYTE),
  TRAN_TYPE      CHAR(5 BYTE),
  ALLOC_NO       NUMBER(10),
  TSF_NO         NUMBER(10),
  ITEM           CHAR(25 BYTE),
  QTY_FULFILLED  NUMBER(20,4),
  PROCESSED      CHAR(1),
  CREATE_DATETIME DATE,
  PROCESSED_DATE DATE,
  ERROR_IND      CHAR(1)
)
TABLESPACE RETEK_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


create or replace public synonym SMR_RMS_INT_ALC_TSF_FULFIL_IMP for RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP;


GRANT  INSERT, SELECT, UPDATE ON RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP TO svc_int_rms;

CREATE INDEX RMS13.SMR_RMS_INT_ALC_TSF_FIL_IMP_I1 ON RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP
(ALLOC_NO)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX RMS13.SMR_RMS_INT_ALC_TSF_FIL_IMP_I2 ON RMS13.SMR_RMS_INT_ALC_TSF_FULFIL_IMP
(TSF_NO)
LOGGING
TABLESPACE RETEK_INDEX
PCTFREE    10
INITRANS   12
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
