drop table RMS13.SMR_BULK_ORDER_NOT_SPLIT;
create table RMS13.SMR_BULK_ORDER_NOT_SPLIT( order_no number(10),
                                       tot_qty_ordered number(12,4),
                                       tot_allocated_qty number(12,4),
                                       tot_qty_heldback number(12,4),
                                       create_datetime date,
                                       username varchar2(100));


drop table RMS13.SMR_REALLOC_ORDHEAD;
create table RMS13.SMR_REALLOC_ORDHEAD as (select * from ordhead where 1=2);
alter table RMS13.SMR_REALLOC_ORDHEAD add (create_datetime date);
alter table RMS13.SMR_REALLOC_ORDHEAD add (username varchar2(100));

drop table RMS13.SMR_REALLOC_ORDSKU;
create table RMS13.SMR_REALLOC_ORDSKU as (select * from ordsku where 1=2);
alter table RMS13.SMR_REALLOC_ORDSKU add (create_datetime date);
alter table RMS13.SMR_REALLOC_ORDSKU add (username varchar2(100));

drop table RMS13.SMR_REALLOC_ORDLOC;
create table RMS13.SMR_REALLOC_ORDLOC as (select * from ordloc where 1=2);
alter table RMS13.SMR_REALLOC_ORDLOC add (create_datetime date);
alter table RMS13.SMR_REALLOC_ORDLOC add (username varchar2(100));

drop table RMS13.SMR_REALLOC_ALLOC_HEADER;
create table RMS13.SMR_REALLOC_ALLOC_HEADER as (select * from alloc_header where 1=2);
alter table RMS13.SMR_REALLOC_ALLOC_HEADER add (create_datetime date);
alter table RMS13.SMR_REALLOC_ALLOC_HEADER add (username varchar2(100));

drop table RMS13.SMR_REALLOC_ALLOC_DETAIL;
create table RMS13.SMR_REALLOC_ALLOC_DETAIL as (select * from alloc_detail where 1=2);
alter table RMS13.SMR_REALLOC_ALLOC_DETAIL add (create_datetime date);
alter table RMS13.SMR_REALLOC_ALLOC_DETAIL add (username varchar2(100));


drop table RMS13.SMR_REALLOC_WH_PO_DTL;
create table RMS13.SMR_REALLOC_WH_PO_DTL as (select * from SMR_RMS_WH_PO_DTL_EXP where 1=2);
alter table RMS13.SMR_REALLOC_WH_PO_DTL add (create_datetime date);
alter table RMS13.SMR_REALLOC_WH_PO_DTL add (username varchar2(100));

drop table RMS13.SMR_REALLOC_WH_PO_HDR;
create table RMS13.SMR_REALLOC_WH_PO_HDR as (select * from SMR_RMS_WH_PO_HDR_EXP where 1=2);
alter table RMS13.SMR_REALLOC_WH_PO_HDR add (create_datetime date);
alter table RMS13.SMR_REALLOC_WH_PO_HDR add (username varchar2(100));

drop table RMS13.SMR_REALLOC_EDI_850_860_DTL;
create table RMS13.SMR_REALLOC_EDI_850_860_DTL as (select * from SMR_PO_EDI_850_860_DTL_EXP where 1=2);
alter table RMS13.SMR_REALLOC_EDI_850_860_DTL add (realloc_create_datetime date);
alter table RMS13.SMR_REALLOC_EDI_850_860_DTL add (username varchar2(100));

drop table RMS13.SMR_REALLOC_EDI_850_860_HDR;
create table RMS13.SMR_REALLOC_EDI_850_860_HDR as (select * from SMR_PO_EDI_850_860_HDR_EXP where 1=2);
alter table RMS13.SMR_REALLOC_EDI_850_860_HDR add (realloc_create_datetime date);
alter table RMS13.SMR_REALLOC_EDI_850_860_HDR add (username varchar2(100));


CREATE OR REPLACE PUBLIC SYNONYM SMR_BULK_ORDER_NOT_SPLIT FOR RMS13.SMR_BULK_ORDER_NOT_SPLIT;
GRANT SELECT ON SMR_BULK_ORDER_NOT_SPLIT TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_BULK_ORDER_NOT_SPLIT TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ORDHEAD FOR RMS13.SMR_REALLOC_ORDHEAD;
GRANT SELECT ON SMR_REALLOC_ORDHEAD TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ORDHEAD TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ORDSKU FOR RMS13.SMR_REALLOC_ORDSKU;
GRANT SELECT ON SMR_REALLOC_ORDSKU TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ORDSKU TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ORDSKU FOR RMS13.SMR_REALLOC_ORDSKU;
GRANT SELECT ON SMR_REALLOC_ORDSKU TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ORDSKU TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ORDLOC FOR RMS13.SMR_REALLOC_ORDLOC;
GRANT SELECT ON SMR_REALLOC_ORDLOC TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ORDLOC TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ALLOC_HEADER FOR RMS13.SMR_REALLOC_ALLOC_HEADER;
GRANT SELECT ON SMR_REALLOC_ALLOC_HEADER TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ALLOC_HEADER TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_ALLOC_DETAIL FOR RMS13.SMR_REALLOC_ALLOC_DETAIL;
GRANT SELECT ON SMR_REALLOC_ALLOC_DETAIL TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_ALLOC_DETAIL TO RMS13_UPDATE;  


CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_WH_PO_DTL FOR RMS13.SMR_REALLOC_WH_PO_DTL;
GRANT SELECT ON SMR_REALLOC_WH_PO_DTL TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_WH_PO_DTL TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_WH_PO_HDR FOR RMS13.SMR_REALLOC_WH_PO_HDR;
GRANT SELECT ON SMR_REALLOC_WH_PO_HDR TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_WH_PO_HDR TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_EDI_850_860_DTL FOR RMS13.SMR_REALLOC_EDI_850_860_DTL;
GRANT SELECT ON SMR_REALLOC_EDI_850_860_DTL TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_EDI_850_860_DTL TO RMS13_UPDATE;  

CREATE OR REPLACE PUBLIC SYNONYM SMR_REALLOC_EDI_850_860_HDR FOR RMS13.SMR_REALLOC_EDI_850_860_HDR;
GRANT SELECT ON SMR_REALLOC_EDI_850_860_HDR TO SMR_READONLY,SVC_SMRREP,BI_RMS_USER,RMS13_SELECT;
GRANT DELETE, INSERT, UPDATE ON SMR_REALLOC_EDI_850_860_HDR TO RMS13_UPDATE;  



-- updated $MMHOME/oracle/lib/src/std_len.h LEN_ORDER_NO from 8 to 10

-- null default_wh's e.g. 799 causes totals to not match allocated totals (if allocated to 799)

